### ISSUE TITLE
Something broken in React Dev Tools

### ISSUE THREAD

**Issue by SnO2WMaN** [ivanhofer/typesafe-i18n#83] opened 2021-09-20 14:32 UTC
When I try to debug a component with `useContext(I18nContext)` (maybe) in React Dev Tools, a browser extension, I got an error like the below image (`Uncaught TypeError: e.split is not a function`) occurred.

![2021 09 20_23 19 54](https://user-images.githubusercontent.com/15155608/134018683-1ca6dfc8-96e9-4bad-83fe-4ce30bf6d795.png)

I don't know the cause of this error, and perhaps other people are getting the same error. Or is it a problem in my environment?

It can reproduce it by launching the React example ( https://github.com/ivanhofer/typesafe-i18n/tree/main/examples/react ) and opening the dev tools. (I checked in Chrome and Firefox and occurred error in both browser)

**Comment by ivanhofer** [comment] 2021-09-21 05:32
Hi @SnO2WMaN,
it is an issue within the React Dev Tools. Right where the code fails there is this comment:

![image](https://user-images.githubusercontent.com/21335119/134116423-e5c39cc5-0ce9-4e2e-a8e7-bebb5595a44d.png)

It links to this issue: https://github.com/facebook/react/issues/21654 
It is closed but apparently not completely resolved yet.

**Comment by ivanhofer** [comment] 2021-09-21 05:42
I have created a PR that fixes the issue: https://github.com/facebook/react/pull/22380

**Comment by SnO2WMaN** [comment] 2021-09-21 06:44
wow very speedy thanks!

**Comment by ivanhofer** [comment] 2022-07-10 07:54
I can't reproduce this anymore. I'm assuming the bug was fixed in the React Dev Tools.

**Closed by ivanhofer** 2022-07-10 07:54 UTC
Labels: external-issue
